# using jbod strategy as storage
# https://cwiki.apache.org/confluence/display/KAFKA/KIP-112%3A+Handle+disk+failure+for+JBOD
# https://github.com/jmxtrans/jmxtrans
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  # kafka cluster name
  name: edh
spec:
  kafka:
    # broker version
    version: 3.7.1
    # initial replicas
    replicas: 2
    # provision lbs
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      default.replication.factor: 1
      num.partitions: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.7"
      inter.broker.protocol.version: "3.7"
      log.retention.hours: 2160
    storage:
      type: ephemeral
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
        - id: 1
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
    # resource limitation
    # -xms -xmx set as same as resources [limit]
    resources:
      requests:
        memory: 128Mi
        cpu: "500m"
      limits:
        memory: 1Gi
        cpu: "1000m"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  # zookeeper information
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      # requests and limits
      requests:
        memory: 128Mi
        cpu: "250m"
      limits:
        memory: 1Gi
        cpu: "500m"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: cruise-control-metrics
          key: metrics-config.yml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
