apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: mongodb
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: "https://github.com/brunoldqueiroz/twitch-emotes.git"
    path: k8s/helms/mongodb/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
